title: ivanka trump 2025.com
description: 'ivanka trump social team '
social_link: face book
social_username: ivanka trump 2025
github_repo: athena
github_username: ivanka trump 2025
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /ivanka_trump_2025_com
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
